// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxS9yWA988SG5sVY0YPxLNkStOo3O25M',
    appId: '1:717550852399:web:076ba6a0da4a9428c6a9da',
    messagingSenderId: '717550852399',
    projectId: 'locate-alert',
    authDomain: 'locate-alert.firebaseapp.com',
    storageBucket: 'locate-alert.appspot.com',
    measurementId: 'G-0D6XWNDVD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1m9ol-i9Kpr9wKhTZnjg51fP7bM7Euro',
    appId: '1:717550852399:android:c4487a93491b0152c6a9da',
    messagingSenderId: '717550852399',
    projectId: 'locate-alert',
    storageBucket: 'locate-alert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByBk3B4p8I6ZGiZfd_pcilZhSQTAhS2N0',
    appId: '1:717550852399:ios:531488c50db3aa53c6a9da',
    messagingSenderId: '717550852399',
    projectId: 'locate-alert',
    storageBucket: 'locate-alert.appspot.com',
    iosBundleId: 'com.qoofhouse.collaralert.elephantCollar',
  );
}
